version: "3"

services:

  keycloak:
    image: jboss/keycloak:16.0.0
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json"
    volumes:
      - ./keycloak/realm.json:/opt/jboss/keycloak/imports/realm.json
